#.travis.yml
language: node_js #指定语言
node_js: 12 #指定node版本
install:
  - npm install #由于travis-ci中的node项目默认就会执行npm install，因此也可以省略。如果存在yarn.lock文件会优先执行yarn。如果存在npm ci指令也会优先执行。

script: #执行的命令
  - npm run lint
  - npm run test
  - npm run build

deploy: #发布部分
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - npm run semantic-release #执行发布指令
